//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalOceanCP.ProfileSetting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Profiles : global::System.Configuration.ApplicationSettingsBase {
        
        private static Profiles defaultInstance = ((Profiles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Profiles())));
        
        public static Profiles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProfileList {
            get {
                return ((string)(this["ProfileList"]));
            }
            set {
                this["ProfileList"] = value;
            }
        }
    }
}
